routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();




Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function() {

    Route::get('/home', 'HomeController@index')->name('admin.home');


    /**
     * created by thuan
     * created at 12/07/2020
     * Description: Display Dashboard Home
     */
    // Route::get('/','HomeController@home');

    /**
     * created by thuan
     * created at 12/07/2020
     * Description: CRUD for VendorController
     */
    Route::resource('/vendor', 'VendorController');
    Route::post('/vendor/destroyMass','VendorController@destroyMass')->name('vendor.destroyMass');

    /**
     * created by thuan
     * created at 12/07/2020
     * Description: CRUD for VendorController
     */
    Route::resource('/category', 'CategoryController');
    Route::post('/category/destroyMass','CategoryController@destroyMass')->name('category.destroyMass');

    /**
     * created by thuan
     * created at 12/07/2020
     * Description: CRUD for VendorController
     */
    Route::resource('/producttype', 'ProductTypeController');
    Route::post('/producttype/destroyMass','ProductTypeController@destroyMass')->name('producttype.destroyMass');


    /**
     * created by thuan
     * created at 12/07/2020
     * Description: CRUD for VendorController
     */
    Route::resource('/product', 'ProductController');
    Route::post('/product/destroyMass','ProductController@destroyMass')->name('product.destroyMass');
    Route::get('/ajaxproducttypes','ProductController@getProductTypeByCategory')->name('product.getProductType');


    /**
     * created by thuan
     * created at 12/07/2020
     * Description: CRUD for VendorController
     */
    Route::resource('/order', 'OrderController');
    Route::get('/orderdetail/{order_id}','OrderController@show')->name('order.orderdetail');
    Route::post('/order/destroyMass','OrderController@destroyMass')->name('order.destroyMass');
    // Route::get('/ajaxproducttypes','ProductController@getProductTypeByCategory')->name('product.getProductType');

     /**
     * created by thuan
     * created at 12/07/2020
     * Description: CRUD for VendorController
     */
    // Route::resource('/orderdetail', 'OrderDetailController');
    // Route::post('/orderdetail/destroyMass','OrderController@destroyMass')->name('order.destroyMass');
    // Route::get('/ajaxproducttypes','ProductController@getProductTypeByCategory')->name('product.getProductType');



});

Route::get('/login','PageController@login')->name('page.login');
Route::post('/login','PageController@handleLogin')->name('page.handelLogin');
Route::get('/register','PageController@register')->name('page.register');
Route::post('/register','PageController@handleRegister')->name('page.handleRegister');
Route::get('/logout','PageController@logout')->name('page.logout');

Route::get('/','PageController@index')->name('page.home');
Route::get('/shop','PageController@shop')->name('page.shop');
Route::get('/cart','PageController@cart')->name('page.cart');
Route::get('/ajaxcartproducts','PageController@getProductCart');

Route::post('/ajaxorderproducts','OrderController@handleOrderAjax');

app/Http/Controllers/ProductTypeController.php
<?php

namespace App\Http\Controllers;

use App\Model\Category;
use App\Model\ProductType;
use Illuminate\Http\Request;

class ProductTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $producttypes = ProductType::orderBy('created_at','desc')->paginate(10);
        return view('admin.producttype.index',['producttypes'=>$producttypes]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $categories = Category::all();
        return view('admin.producttype.create',['categories'=>$categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'name'=>'required',
            'category_id'=>'required'
            ],[
                'name.required'=>'Please enter product type name',
                'category_id.required'=>"Please choose category"
            ]
        );

        $fileName = 'default.jpg';
        if ($request->image) {
            try {
                $fileName = 'producttype-'.time().'.'.$request->image->extension();
                $request->image->move(public_path('uploads'), $fileName);
            } catch (\Throwable $th) {
                throw $th;
                $errors = true;
            }

        }

        try {
            $productType = new ProductType();
            $productType->name = $request->name;
            $productType->image = $fileName;
            $productType->category_id = $request->category_id;
            $productType->save();
        } catch (\Throwable $e) {
            return redirect()->back()->with('failed','Create Failed');
        }


        return redirect()->back()->with('success','Create Successfully');


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\ProductType  $productType
     * @return \Illuminate\Http\Response
     */
    public function show(ProductType $productType)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\ProductType  $productType
     * @return \Illuminate\Http\Response
     */
    public function edit(ProductType $productType,Request $request)
    {
        //
        $categories = Category::all();
        $productType = ProductType::find($request->id);
        return view('admin.producttype.edit',['categories'=>$categories,'productType'=>$productType]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\ProductType  $productType
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        //
        $request->validate([
            'name'=>'required',
            'category_id'=>'required'
            ],[
                'name.required'=>'Please enter product type name',
                'category_id.required'=>"Please choose category"
            ]
        );

        $fileName = 'default.jpg';
        if ($request->image) {
            try {
                $fileName = 'producttype-'.time().'.'.$request->image->extension();
                $request->image->move(public_path('uploads'), $fileName);
            } catch (\Throwable $th) {
                throw $th;
                $errors = true;
            }

        }
        try {
            $productType = ProductType::where('id',$request->id)->first();

            $productType->name = $request->name;
            if($request->image){
                $productType->image = $fileName;
            }
            $productType->category_id = $request->category_id;
            $productType->save();
        } catch (\Throwable $e) {
            return redirect()->back()->with('failed','Update Failed');
        }


        return redirect()->back()->with('success','Update Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\ProductType  $productType
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        //
        try {
            ProductType::where('id',$request->id)->delete();
        } catch (\Throwable $th) {
            return redirect()->back()->with('failed','Delete  failed!!!');
        }

        return redirect()->back()->with('success','Delete  success!');


    }

     /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Vendor  $vendor
     * @return \Illuminate\Http\Response
     */
    public function destroyMass(Request $request)
    {
        $errors = null;
        try {
            //...
            ProductType::destroy($request->ids);
        } catch (\Throwable $th) {
            $errors = "failed";
        }

        return response()->json([
            'state'=>$errors
        ]);
    }
}

resources/views/admin/producttype/create.blade.php
@extends('admin.layouts.master')
<link rel="stylesheet" href="{{ asset('assets/adminForm.css') }}">

@section('content')
<div class="content">
    <div class="kt--bg-header kt--pd-20">
            <h3>Product Type</h3>
    </div>
    <div class="kt--pd-100">
        <div>
            @if(session()->has('success'))
            <div class="alert alert-success" >
                {{ session()->get('success') }}
            </div>
            @endif
            @if(session()->has('failed'))
            <div class="alert alert-danger" >
                {{ session()->get('failed') }}
            </div>
            @endif
        </div>
        <form method="POST" action="{{ route('producttype.store')}}" enctype="multipart/form-data">
            @csrf
            <div class="form-row kt--mgb-20">
                <div class="form-group col-md-6 is-focused">
                    <div class="input-group mb-3">
                        <select name="category_id" class="custom-select" id="inputGroupSelect02">
                          <option selected >Choose...</option>
                          @foreach ($categories as $producttype)
                            <option value="{{$producttype->id}}">{{$producttype->name}}</option>
                          @endforeach
                        </select>

                    </div>
                </div>

            </div>
            <div class="form-group is-focused kt--mgb-20">
                    <label for="inputName">Name</label>
                    <input name="name" value="{{old('name')}}" type="text" class="form-control form-control @error('name') is-invalid @enderror" id="inputName">
                    @error('name')
                        <span class="error invalid-feedback">{{$message}}</span>
                    @enderror
            </div>

            <div class="custom-file kt--mgt-20" id="uploadForm">
                <input type="file" name="image"  id="file">
            </div>
            <div class="kt--mgt-20">
                <button type="submit" class="btn btn-primary float-right">Create</button>
            </div>

          </form>
    </div>

</div>
@endsection

resources/views/admin/producttype/edit.blade.php
@extends('admin.layouts.master')
<link rel="stylesheet" href="{{ asset('assets/adminForm.css') }}">

@section('content')
<div class="content">
    <div class="kt--bg-header kt--pd-20">
            <h3>Product Type</h3>
    </div>
    <div class="kt--pd-100">
        <div>
            @if(session()->has('success'))
            <div class="alert alert-success" >
                {{ session()->get('success') }}
            </div>
            @endif
            @if(session()->has('failed'))
            <div class="alert alert-danger" >
                {{ session()->get('failed') }}
            </div>
            @endif
        </div>
        <form method="POST" action="{{ route('producttype.update',['producttype'=>$productType->id])}}" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <input hidden name="id" value="{{$productType->id}}" type="text" class="form-control form-control @error('name') is-invalid @enderror" id="inputName">

            <div class="form-row kt--mgb-20">
                <div class="form-group col-md-6 is-focused">
                    <div class="input-group mb-3">
                        <select name="category_id" class="custom-select" id="inputGroupSelect02">
                          <option value="{{$productType->category->id}}" selected >{{$productType->category->name}}</option>
                          @foreach ($categories as $category)
                            <option value="{{$category->id}}">{{$category->name}}</option>
                          @endforeach
                        </select>

                    </div>
                </div>

            </div>
            <div class="form-group is-focused kt--mgb-20">
                    <label for="inputName">Name</label>
                    <input name="name" value="{{$productType->name}}" type="text" class="form-control form-control @error('name') is-invalid @enderror" id="inputName">
                    @error('name')
                        <span class="error invalid-feedback">{{$message}}</span>
                    @enderror
            </div>

            <div class="custom-file kt--mgt-20" id="uploadForm">
                <input type="file" name="image"  id="file">
            </div>
            <img src="{{ asset('uploads/'.$productType->image) }}" width="200px" alt="" srcset="">

            <div class="kt--mgt-20">
                <button type="submit" class="btn btn-primary float-right">Create</button>
            </div>

          </form>
    </div>

</div>
@endsection

resources/views/admin/producttype/index.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
                <div class="col-md-6">
                   <button class="btn btn-danger" id='producttype-deleteAllCheckbox' >Delete Selected</button>
                </div>
                <div class="col-md-6 ">
                    <a class="btn btn-success float-right" href="{{ route('producttype.create') }}">
                    Add
                    </a>
                </div>
        </div>
        <div>
            @if(session()->has('success'))
            <div class="alert alert-success" >
                {{ session()->get('success') }}
            </div>
            @endif
            @if(session()->has('failed'))
            <div class="alert alert-success" >
                {{ session()->get('failed') }}
            </div>
            @endif
        </div>
      <div class="row">
        <div class="col-md-12">
          <div class="card">

            <div class="card-body">
              <div class="table-responsive">
                <table class="table">
                  <thead class=" text-primary">
                    <tr>
                    <th>
                        <input type="checkbox" name="" id="producttype-selectAllCheckbox">
                    </th>
                    <th>
                      ID
                    </th>
                    <th>
                      Name
                    </th>
                    <th>
                      Category
                    </th>
                    <th>
                      Image
                    </th>
                    <th>
                        Setting
                    </th>
                  </tr></thead>
                  <tbody>

                    @foreach ($producttypes as $key => $producttype)
                        <tr>
                            <td>
                                <input type="checkbox" name="producttype[]" id="" value="{{$producttype->id}}">
                            </td>
                            <td><p>{{$key+1}}</p></td>
                            <td><p>{{$producttype->name}}</p></td>
                            <td> <p class="badge badge-info">{{$producttype->category->name}}</p> </td>
                            <td>
                                <img src="{{ asset('uploads/'.$producttype->image) }}" width="100" alt="" srcset="">
                            </td>
                            <td style="width: 20%">
                                <a href="producttype/{{$producttype->id}}/edit?id={{$producttype->id}}" class="btn btn-primary">
                                        <span class="material-icons">construction</span>
                                </a>
                                <button id="producttype-{{$producttype->id}}" onclick=confirmDelete({{$producttype->id}},'producttype') data-id="{{$producttype->id}}" data-name="{{$producttype->name}}" class="btn btn-danger">
                                    <span class="material-icons">delete</span>
                                    <form action="{{ route('producttype.destroy',['producttype'=>$producttype])}}" hidden method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <input name="id" type="text"  value="{{$producttype->id}}">
                                    </form>
                                </button>

                            </td>
                        </tr>
                    @endforeach


                  </tbody>
                </table>
                <div style="display:flex;justify-content: center">
                    {{$producttypes->links()}}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


@endsection