routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();




Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function() {

    Route::get('/home', 'HomeController@index')->name('admin.home');


    /**
     * created by thuan
     * created at 12/07/2020
     * Description: Display Dashboard Home
     */
    // Route::get('/','HomeController@home');

    /**
     * created by thuan
     * created at 12/07/2020
     * Description: CRUD for VendorController
     */
    Route::resource('/vendor', 'VendorController');
    Route::post('/vendor/destroyMass','VendorController@destroyMass')->name('vendor.destroyMass');

    /**
     * created by thuan
     * created at 12/07/2020
     * Description: CRUD for VendorController
     */
    Route::resource('/category', 'CategoryController');
    Route::post('/category/destroyMass','CategoryController@destroyMass')->name('category.destroyMass');

    /**
     * created by thuan
     * created at 12/07/2020
     * Description: CRUD for VendorController
     */
    Route::resource('/producttype', 'ProductTypeController');
    Route::post('/producttype/destroyMass','ProductTypeController@destroyMass')->name('producttype.destroyMass');


    /**
     * created by thuan
     * created at 12/07/2020
     * Description: CRUD for VendorController
     */
    Route::resource('/product', 'ProductController');
    Route::post('/product/destroyMass','ProductController@destroyMass')->name('product.destroyMass');
    Route::get('/ajaxproducttypes','ProductController@getProductTypeByCategory')->name('product.getProductType');


    /**
     * created by thuan
     * created at 12/07/2020
     * Description: CRUD for VendorController
     */
    Route::resource('/order', 'OrderController');
    Route::get('/orderdetail/{order_id}','OrderController@show')->name('order.orderdetail');
    Route::post('/order/destroyMass','OrderController@destroyMass')->name('order.destroyMass');
    // Route::get('/ajaxproducttypes','ProductController@getProductTypeByCategory')->name('product.getProductType');

     /**
     * created by thuan
     * created at 12/07/2020
     * Description: CRUD for VendorController
     */
    // Route::resource('/orderdetail', 'OrderDetailController');
    // Route::post('/orderdetail/destroyMass','OrderController@destroyMass')->name('order.destroyMass');
    // Route::get('/ajaxproducttypes','ProductController@getProductTypeByCategory')->name('product.getProductType');



});

Route::get('/login','PageController@login')->name('page.login');
Route::post('/login','PageController@handleLogin')->name('page.handelLogin');
Route::get('/register','PageController@register')->name('page.register');
Route::post('/register','PageController@handleRegister')->name('page.handleRegister');
Route::get('/logout','PageController@logout')->name('page.logout');

Route::get('/','PageController@index')->name('page.home');
Route::get('/shop','PageController@shop')->name('page.shop');
Route::get('/cart','PageController@cart')->name('page.cart');
Route::get('/ajaxcartproducts','PageController@getProductCart');

Route::post('/ajaxorderproducts','OrderController@handleOrderAjax');

resources/views/admin/layouts/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
      <nav class="float-left">
        <ul>
          <li>
            <a href="https://www.creative-tim.com">
              Creative Tim
            </a>
          </li>
          <li>
            <a href="https://creative-tim.com/presentation">
              About Us
            </a>
          </li>
          <li>
            <a href="http://blog.creative-tim.com">
              Blog
            </a>
          </li>
          <li>
            <a href="https://www.creative-tim.com/license">
              Licenses
            </a>
          </li>
        </ul>
      </nav>
      <div class="copyright float-right">
        ©
        <script>
          document.write(new Date().getFullYear())
        </script>2020, made with <i class="material-icons">favorite</i> by
        <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a> for a better web.
      </div>
    </div>
  </footer>

   <!--   Core JS Files   -->
   <script src="{{ asset('admin_dashboard/assets/js/core/jquery.min.js')}}"></script>
   <script src="{{ asset('admin_dashboard/assets/js/core/popper.min.js')}}"></script>
   <script src="{{asset('admin_dashboard/assets/js/core/bootstrap-material-design.min.js')}}"></script>
   <script src=" {{ asset('admin_dashboard/assets/js/plugins/perfect-scrollbar.jquery.min.js') }}"></script>
   <!-- Plugin for the momentJs  -->
   <script src="{{ asset('admin_dashboard/assets/js/plugins/moment.min.js') }}"></script>
   <!--  Plugin for Sweet Alert -->
   <script src=" {{ asset('admin_dashboard/assets/js/plugins/sweetalert2.js') }}"></script>
   <!-- Forms Validations Plugin -->
   <script src="{{ asset('admin_dashboard/assets/js/plugins/jquery.validate.min.js') }}"></script>
   <!-- Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
   <script src="{{ asset('admin_dashboard/assets/js/plugins/jquery.bootstrap-wizard.js') }}"></script>
   <!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
   <script src="{{ asset('admin_dashboard/assets/js/plugins/bootstrap-selectpicker.js') }}"></script>
   <!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
   <script src="{{ asset('admin_dashboard/assets/js/plugins/bootstrap-datetimepicker.min.js') }}"></script>
   <!--  DataTables.net Plugin, full documentation here: https://datatables.net/  -->
   <script src="{{ asset('admin_dashboard/assets/js/plugins/jquery.dataTables.min.js') }}"></script>
   <!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
   <script src="{{ asset('admin_dashboard/assets/js/plugins/bootstrap-tagsinput.js') }}"></script>
   <!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
   <script src="{{ asset('admin_dashboard/assets/js/plugins/jasny-bootstrap.min.js') }}"></script>
   <!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
   <script src="{{ asset('admin_dashboard/assets/js/plugins/fullcalendar.min.js') }}"></script>
   <!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->
   <script src="{{ asset('admin_dashboard/assets/js/plugins/jquery-jvectormap.js') }}"></script>
   <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
   <script src="{{ asset('admin_dashboard/assets/js/plugins/nouislider.min.js') }}"></script>
   <!-- Include a polyfill for ES6 Promises (optional) for IE11, UC Browser and Android browser support SweetAlert -->
   <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
   <!-- Library for adding dinamically elements -->
   <script src="{{ asset('admin_dashboard/assets/js/plugins/arrive.min.js') }}"></script>
   <!--  Google Maps Plugin    -->
   {{--  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>  --}}
   <!-- Chartist JS -->
   <script src="{{ asset('admin_dashboard/assets/js/plugins/chartist.min.js') }}"></script>
   <!--  Notifications Plugin    -->
   <script src="{{ asset('admin_dashboard/assets/js/plugins/bootstrap-notify.js') }}"></script>
   <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
   <script src="{{ asset('admin_dashboard/assets/js/material-dashboard.js?v=2.1.2') }}" type="text/javascript"></script>
   <!-- Material Dashboard DEMO methods, don't include it in your project! -->
   <script src="{{ asset('admin_dashboard/assets/demo/demo.js') }}"></script>
   <script>
     $(document).ready(function() {
       $().ready(function() {
         $sidebar = $('.sidebar');

         $sidebar_img_container = $sidebar.find('.sidebar-background');

         $full_page = $('.full-page');

         $sidebar_responsive = $('body > .navbar-collapse');

         window_width = $(window).width();

         fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();

         if (window_width > 767 && fixed_plugin_open == 'Dashboard') {
           if ($('.fixed-plugin .dropdown').hasClass('show-dropdown')) {
             $('.fixed-plugin .dropdown').addClass('open');
           }

         }

         $('.fixed-plugin a').click(function(event) {
           // Alex if we click on switch, stop propagation of the event, so the dropdown will not be hide, otherwise we set the  section active
           if ($(this).hasClass('switch-trigger')) {
             if (event.stopPropagation) {
               event.stopPropagation();
             } else if (window.event) {
               window.event.cancelBubble = true;
             }
           }
         });

         $('.fixed-plugin .active-color span').click(function() {
           $full_page_background = $('.full-page-background');

           $(this).siblings().removeClass('active');
           $(this).addClass('active');

           var new_color = $(this).data('color');

           if ($sidebar.length != 0) {
             $sidebar.attr('data-color', new_color);
           }

           if ($full_page.length != 0) {
             $full_page.attr('filter-color', new_color);
           }

           if ($sidebar_responsive.length != 0) {
             $sidebar_responsive.attr('data-color', new_color);
           }
         });

         $('.fixed-plugin .background-color .badge').click(function() {
           $(this).siblings().removeClass('active');
           $(this).addClass('active');

           var new_color = $(this).data('background-color');

           if ($sidebar.length != 0) {
             $sidebar.attr('data-background-color', new_color);
           }
         });

         $('.fixed-plugin .img-holder').click(function() {
           $full_page_background = $('.full-page-background');

           $(this).parent('li').siblings().removeClass('active');
           $(this).parent('li').addClass('active');


           var new_image = $(this).find("img").attr('src');

           if ($sidebar_img_container.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
             $sidebar_img_container.fadeOut('fast', function() {
               $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
               $sidebar_img_container.fadeIn('fast');
             });
           }

           if ($full_page_background.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
             var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

             $full_page_background.fadeOut('fast', function() {
               $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
               $full_page_background.fadeIn('fast');
             });
           }

           if ($('.switch-sidebar-image input:checked').length == 0) {
             var new_image = $('.fixed-plugin li.active .img-holder').find("img").attr('src');
             var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

             $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
             $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
           }

           if ($sidebar_responsive.length != 0) {
             $sidebar_responsive.css('background-image', 'url("' + new_image + '")');
           }
         });

         $('.switch-sidebar-image input').change(function() {
           $full_page_background = $('.full-page-background');

           $input = $(this);

           if ($input.is(':checked')) {
             if ($sidebar_img_container.length != 0) {
               $sidebar_img_container.fadeIn('fast');
               $sidebar.attr('data-image', '#');
             }

             if ($full_page_background.length != 0) {
               $full_page_background.fadeIn('fast');
               $full_page.attr('data-image', '#');
             }

             background_image = true;
           } else {
             if ($sidebar_img_container.length != 0) {
               $sidebar.removeAttr('data-image');
               $sidebar_img_container.fadeOut('fast');
             }

             if ($full_page_background.length != 0) {
               $full_page.removeAttr('data-image', '#');
               $full_page_background.fadeOut('fast');
             }

             background_image = false;
           }
         });

         $('.switch-sidebar-mini input').change(function() {
           $body = $('body');

           $input = $(this);

           if (md.misc.sidebar_mini_active == true) {
             $('body').removeClass('sidebar-mini');
             md.misc.sidebar_mini_active = false;

             $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar();

           } else {

             $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar('destroy');

             setTimeout(function() {
               $('body').addClass('sidebar-mini');

               md.misc.sidebar_mini_active = true;
             }, 300);
           }

           // we simulate the window Resize so the charts will get updated in realtime.
           var simulateWindowResize = setInterval(function() {
             window.dispatchEvent(new Event('resize'));
           }, 180);

           // we stop the simulation of Window Resize after the animations are completed
           setTimeout(function() {
             clearInterval(simulateWindowResize);
           }, 1000);

         });
       });
     });
   </script>
   <script>
     $(document).ready(function() {
       // Javascript method's body can be found in assets/js/demos.js
       md.initDashboardPageCharts();

     });
   </script>

   <script src="{{ asset('assets/style.js') }}"></script>

 </body>

 </html>

resources/views/admin/layouts/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <head>
        <meta charset="utf-8">
        <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
        <link rel="icon" type="image/png" href="../assets/img/favicon.png">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>
          Material Dashboard
        </title>
        <meta content="width=device-width, initial-scale=1.0, shrink-to-fit=no" name="viewport">
        <!--     Fonts and icons     -->
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
        <!-- CSS Files -->
        <link href="{{ asset('admin_dashboard/assets/css/material-dashboard.css?v=2.1.2') }}"  rel="stylesheet">
        {{-- <link href="{{ asset(' assets/demo/demo.css') }}" rel="stylesheet"> --}}
        {{-- <script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/41/5/intl/vi_ALL/common.js"></script>
        <script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/41/5/intl/vi_ALL/util.js"></script></head> --}}
</head>
<body>

resources/views/admin/layouts/leftSide.blade.php
<div class="sidebar" data-color="purple" data-background-color="white" data-image="../assets/img/sidebar-1.jpg">

    <div class="logo"><a href="http://www.creative-tim.com" class="simple-text logo-normal">
        My Team
      </a></div>
    <div class="sidebar-wrapper ps-container ps-theme-default" data-ps-id="04c052ed-e85a-6439-c709-f327d66ff891">
      <form class="navbar-form">
            <span class="bmd-form-group"><div class="input-group no-border">
              <input type="text" value="" class="form-control" placeholder="Search...">
              <button type="submit" class="btn btn-white btn-round btn-just-icon">
                <i class="material-icons">search</i>
                <div class="ripple-container"></div>
              </button>
            </div></span>
          </form><ul class="nav navbar-nav nav-mobile-menu">
            <li class="nav-item">
              <a class="nav-link" href="javascript:;">
                <i class="material-icons">dashboard</i>
                <p class="d-lg-none d-md-block">
                  Stats
                </p>
              </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="material-icons">notifications</i>
                <span class="notification">5</span>
                <p class="d-lg-none d-md-block">
                  Some Actions
                </p>
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Mike John responded to your email</a>
                <a class="dropdown-item" href="#">You have 5 new tasks</a>
                <a class="dropdown-item" href="#">You are now friend with Andrew</a>
                <a class="dropdown-item" href="#">Another Notification</a>
                <a class="dropdown-item" href="#">Another One</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link" href="javascript:;" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="material-icons">person</i>
                <p class="d-lg-none d-md-block">
                  Account
                </p>
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                <a class="dropdown-item" href="#">Profile</a>
                <a class="dropdown-item" href="#">Settings</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Log out</a>
              </div>
            </li>
          </ul><ul class="nav">
        <li class="nav-item active  ">
          <a class="nav-link" href="./dashboard.html">
            <i class="material-icons">dashboard</i>
            <p>Dashboard</p>
          </a>
        </li>

        <li class="nav-item ">
            <a class="nav-link" href="{{route('vendor.index')}}">
              <i class="material-icons">Vendor</i>
              <p>Vendor</p>
            </a>
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="{{route('category.index')}}">
              <i class="material-icons">Category</i>
              <p>Category</p>
            </a>
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="{{route('producttype.index')}}">
              <i class="material-icons">Productype</i>
              <p>Product Type</p>
            </a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="{{route('product.index')}}">
            <i class="material-icons">Product</i>
            <p>Product</p>
          </a>
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="{{route('order.index')}}">
              <i class="material-icons">Order</i>
              <p>Order</p>
            </a>
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="./user.html">
              <i class="material-icons">Review</i>
              <p>Review</p>
            </a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="./typography.html">
            <i class="material-icons">library_books</i>
            <p>Typography</p>
          </a>
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="./user.html">
              <i class="material-icons">User</i>
              <p>User</p>
            </a>
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="./user.html">
              <i class="material-icons">person</i>
              <p>User Profile</p>
            </a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="./icons.html">
            <i class="material-icons">bubble_chart</i>
            <p>Icons</p>
          </a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="./map.html">
            <i class="material-icons">location_ons</i>
            <p>Maps</p>
          </a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="./notifications.html">
            <i class="material-icons">notifications</i>
            <p>Notifications</p>
          </a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="./rtl.html">
            <i class="material-icons">language</i>
            <p>RTL Support</p>
          </a>
        </li>
        <li class="nav-item active-pro ">
          <a class="nav-link" href="./upgrade.html">
            <i class="material-icons">unarchive</i>
            <p>Upgrade to PRO</p>
          </a>
        </li>
      </ul>
    <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 0px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 0px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
  <div class="sidebar-background" style="background-image: url(../assets/img/sidebar-1.jpg) "></div></div>

resources/views/admin/layouts/master.blade.php
@include('admin/layouts/header')
@include('admin/layouts/leftSide')

    <div class="wrapper">
        <div class="main-panel">
            @include('admin/layouts/navbar')
            @yield('content')
            @include('admin/layouts/footer')
        </div>
    </div>

resources/views/admin/layouts/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
    <div class="container-fluid">
      <div class="navbar-wrapper">
        <a class="navbar-brand" href="javascript:;">Dashboard<div class="ripple-container"></div></a>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
        <span class="sr-only">Toggle navigation</span>
        <span class="navbar-toggler-icon icon-bar"></span>
        <span class="navbar-toggler-icon icon-bar"></span>
        <span class="navbar-toggler-icon icon-bar"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end">
        <form class="navbar-form">
          <span class="bmd-form-group"><div class="input-group no-border">
            <input type="text" value="" class="form-control" placeholder="Search...">
            <button type="submit" class="btn btn-white btn-round btn-just-icon">
              <i class="material-icons">search</i>
              <div class="ripple-container"></div>
            </button>
          </div></span>
        </form>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="javascript:;">
              <i class="material-icons">dashboard</i>
              <p class="d-lg-none d-md-block">
                Stats
              </p>
            </a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="material-icons">notifications</i>
              <span class="notification">5</span>
              <p class="d-lg-none d-md-block">
                Some Actions
              </p>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Mike John responded to your email</a>
              <a class="dropdown-item" href="#">You have 5 new tasks</a>
              <a class="dropdown-item" href="#">You're now friend with Andrew</a>
              <a class="dropdown-item" href="#">Another Notification</a>
              <a class="dropdown-item" href="#">Another One</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link" href="javascript:;" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="material-icons">person</i>
              <p class="d-lg-none d-md-block">
                Account
              </p>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
              <a class="dropdown-item" href="#">Profile</a>
              <a class="dropdown-item" href="#">Settings</a>
              <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{route('page.logout')}}">Log out</a>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>