routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();




Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function() {

    Route::get('/home', 'HomeController@index')->name('admin.home');


    /**
     * created by thuan
     * created at 12/07/2020
     * Description: Display Dashboard Home
     */
    // Route::get('/','HomeController@home');

    /**
     * created by thuan
     * created at 12/07/2020
     * Description: CRUD for VendorController
     */
    Route::resource('/vendor', 'VendorController');
    Route::post('/vendor/destroyMass','VendorController@destroyMass')->name('vendor.destroyMass');

    /**
     * created by thuan
     * created at 12/07/2020
     * Description: CRUD for VendorController
     */
    Route::resource('/category', 'CategoryController');
    Route::post('/category/destroyMass','CategoryController@destroyMass')->name('category.destroyMass');

    /**
     * created by thuan
     * created at 12/07/2020
     * Description: CRUD for VendorController
     */
    Route::resource('/producttype', 'ProductTypeController');
    Route::post('/producttype/destroyMass','ProductTypeController@destroyMass')->name('producttype.destroyMass');


    /**
     * created by thuan
     * created at 12/07/2020
     * Description: CRUD for VendorController
     */
    Route::resource('/product', 'ProductController');
    Route::post('/product/destroyMass','ProductController@destroyMass')->name('product.destroyMass');
    Route::get('/ajaxproducttypes','ProductController@getProductTypeByCategory')->name('product.getProductType');


    /**
     * created by thuan
     * created at 12/07/2020
     * Description: CRUD for VendorController
     */
    Route::resource('/order', 'OrderController');
    Route::get('/orderdetail/{order_id}','OrderController@show')->name('order.orderdetail');
    Route::post('/order/destroyMass','OrderController@destroyMass')->name('order.destroyMass');
    // Route::get('/ajaxproducttypes','ProductController@getProductTypeByCategory')->name('product.getProductType');

     /**
     * created by thuan
     * created at 12/07/2020
     * Description: CRUD for VendorController
     */
    // Route::resource('/orderdetail', 'OrderDetailController');
    // Route::post('/orderdetail/destroyMass','OrderController@destroyMass')->name('order.destroyMass');
    // Route::get('/ajaxproducttypes','ProductController@getProductTypeByCategory')->name('product.getProductType');



});

Route::get('/login','PageController@login')->name('page.login');
Route::post('/login','PageController@handleLogin')->name('page.handelLogin');
Route::get('/register','PageController@register')->name('page.register');
Route::post('/register','PageController@handleRegister')->name('page.handleRegister');
Route::get('/logout','PageController@logout')->name('page.logout');

Route::get('/','PageController@index')->name('page.home');
Route::get('/shop','PageController@shop')->name('page.shop');
Route::get('/cart','PageController@cart')->name('page.cart');
Route::get('/ajaxcartproducts','PageController@getProductCart');

Route::post('/ajaxorderproducts','OrderController@handleOrderAjax');

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Model\Category;
use App\Model\Product;
use App\Model\ProductType;
use App\Model\Vendor;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $products = Product::orderBy('created_at','desc')->paginate(10);
        return view('admin.product.index',['products'=>$products]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $vendors = Vendor::all();
        $categories = Category::all();
        $producttypes = ProductType::all();
        return view('admin.product.create',['vendors'=>$vendors,'categories'=>$categories,'producttypes'=>$producttypes]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate(
            [
                'name'=>'required',
                'stock'=>'required|numeric',
                'price'=>'required|numeric',
                'vendor_id'=>'required',
                'producttype_id'=>'required',
                'category_id'=>'required'

            ],[
                'name.required'=>'Please enter  name',
                'stock.required'=>'Please enter stock',
                'stock.numeric'=>'Stock should be number',
                'price.required'=>"Please enter price",
                'price.numeric'=>'Price should be number',

            ]
        );

        $fileName = 'default.jpg';
        if ($request->image) {
            try {
                $fileName = 'prodyct-'.time().'.'.$request->image->extension();
                $request->image->move(public_path('uploads'), $fileName);
            } catch (\Throwable $th) {
                throw $th;
                $errors = true;
            }

        }
        try {
            $product = new Product();
            $product->name = $request->name;
            $product->image = $fileName;
            $product->slug = Str::slug($request->name,'-');
            $product->stock = $request->stock;
            $product->price = $request->price;
            $product->description = $request->description;
            $product->producttype_id = $request->category_id;
            $product->vendor_id = $request->vendor_id;
            $product->save();
        } catch (\Throwable $e) {
            return redirect()->back()->with('failed','Create Failed');
        }


        return redirect()->back()->with('success','Create Successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        //
        $vendors = Vendor::all();
        $producttypes = ProductType::all();
        $categories = Category::all();

        return view('admin.product.edit',['product'=>$product,'vendors'=>$vendors,'categories'=>$categories,'producttypes'=>$producttypes]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        //
        $request->validate(
            [
                'name'=>'required',
                'stock'=>'required|numeric',
                'price'=>'required|numeric',
                'vendor_id'=>'required',
                'producttype_id'=>'required',
                'category_id'=>'required'

            ],[
                'name.required'=>'Please enter  name',
                'stock.required'=>'Please enter stock',
                'stock.numeric'=>'Stock should be number',
                'price.required'=>"Please enter price",
                'price.numeric'=>'Price should be number',

            ]
        );

        $fileName = 'default.jpg';
        if ($request->image) {
            try {
                $fileName = 'product-'.time().'.'.$request->image->extension();
                $request->image->move(public_path('uploads'), $fileName);
            } catch (\Throwable $th) {
                throw $th;

            }

        }

        try {

            $product->name = $request->name;
            if($request->image){
                $product->image = $fileName;
            }
            $product->slug = Str::slug($request->name,'-');
            $product->stock = $request->stock;
            $product->price = $request->price;
            $product->description = $request->description;
            $product->producttype_id = $request->category_id;
            $product->vendor_id = $request->vendor_id;
            $product->update();
        } catch (\Throwable $e) {
            return redirect()->back()->with('failed','Update Failed');
        }

        // dd($product);
        return redirect()->back()->with('success','Update Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        //

        try {
            $product->delete();
        } catch (\Throwable $th) {
            return redirect()->back()->with('failed','Delete  failed!!!');
        }

        return redirect()->back()->with('success','Delete  success!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Vendor  $vendor
     * @return \Illuminate\Http\Response
     */
    public function destroyMass(Request $request)
    {
        $errors = null;
        try {
            //...
            Product::destroy($request->ids);
        } catch (\Throwable $th) {
            $errors = "failed";
        }

        return response()->json([
            'state'=>$errors
        ]);
    }



    /**
     * Get producttype by category ajax
     *
     * @param  \App\Model\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function getProductTypeByCategory(Request $request)
    {

        try {
            //code...
            $category_id =  $request->id;
            $producttypes = ProductType::where('category_id',$category_id)->get();

        } catch (\Throwable $th) {
            //throw $th;
            return response()->json('error',404);

        }

        return response()->json([
            'data'=>$producttypes
        ]);

    }
}

resources/views/admin/product/create.blade.php
@extends('admin.layouts.master')
<link rel="stylesheet" href="{{ asset('assets/adminForm.css') }}">

@section('content')
<div class="content">
    <div class="kt--bg-header kt--pd-20">
            <h3>Product</h3>
    </div>
    <div class="kt--pd-100">
        <div>
            @if(session()->has('success'))
            <div class="alert alert-success" >
                {{ session()->get('success') }}
            </div>
            @endif
            @if(session()->has('failed'))
            <div class="alert alert-success" >
                {{ session()->get('failed') }}
            </div>
            @endif
        </div>
        <form method="POST" action="{{ route('product.store')}}" enctype="multipart/form-data">
            @csrf

            <div class="form-row kt--mgb-20">
                <div class="form-group col-md-4 is-focused">
                    <label for="">Category</label>
                    <div class="input-group mb-3">
                        <select id="category" name="category_id" class="custom-select form-control form-control @error('category_id') is-invalid @enderror" id="inputGroupSelect02">
                            <option value="">Choose Category</option>
                        @foreach ($categories as $category)
                            <option value="{{$category->id}}">{{$category->name}}</option>
                        @endforeach
                        </select>
                        @error('category_id')
                        <span class="error invalid-feedback">{{$message}}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group col-md-4 is-focused">
                    <label for="">Product Type</label>
                    <div class="input-group mb-3">
                        <select id="producttype" name="producttype_id" class="custom-select form-control form-control @error('producttype_id') is-invalid @enderror" id="inputGroupSelect02">

                        </select>
                        @error('producttype_id')
                        <span class="error invalid-feedback">{{$message}}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group col-md-4 is-focused">
                    <label for="">Vendor</label>

                    <div class="input-group mb-3">
                        <select id="vendor" name="vendor_id" class="custom-select form-control form-control @error('vendor_id') is-invalid @enderror" id="inputGroupSelect02">
                          @foreach ($vendors as $vendor)
                            <option value="{{$vendor->id}}">{{$vendor->name}}</option>
                          @endforeach

                        </select>
                        @error('vendor_id')
                        <span class="error invalid-feedback">{{$message}}</span>
                        @enderror
                    </div>
                </div>


            </div>


            <div class="form-row kt--mgb-20">
              <div class="form-group col-md-6 is-focused">
                <label for="inputName">Name</label>
                <input name="name" value="{{old('name')}}" type="text" class="form-control form-control @error('name') is-invalid @enderror" id="inputName">
                @error('name')
                    <span class="error invalid-feedback">{{$message}}</span>
                @enderror
              </div>
              <div class="form-group col-md-6 is-focused">
                <label for="inputStock">Stock</label>
                <input name="stock" value="{{old('stock')}}" type="text" class="form-control form-control @error('stock') is-invalid @enderror" id="inputStock">
                @error('stock')
                    <span class="error invalid-feedback">{{$message}}</span>
                @enderror
              </div>
            </div>
            <div class="form-row kt--mgb-20">
                <div class="form-group col-md-6 is-focused">
                  <label for="inputPrice">Price</label>
                  <input name="price" value="{{old('price')}}" type="text" class="form-control form-control @error('price') is-invalid @enderror" id="inputPrice">
                  @error('price')
                      <span class="error invalid-feedback">{{$message}}</span>
                  @enderror
                </div>


            </div>

            <div class="form-row kt--mgb-20">

                <div class="form-group col-md-12 is-focused">
                  <label for="inputDescription">Description</label>
                  <textarea  name="description" rows="6" class="form-control form-control @error('description') is-invalid @enderror" id="inputDescription">
                      {{old('description')}}
                  </textarea>
                  @error('description')
                      <span class="error invalid-feedback">{{$message}}</span>
                  @enderror
                </div>
            </div>


            <div class="custom-file kt--mgt-20" id="uploadForm">
                <input type="file" name="image"  id="file">
            </div>
w

            <div class="kt--mgt-20">
                <button type="submit" class="btn btn-primary float-right">Create</button>
            </div>

          </form>
    </div>

</div>


@endsection

resources/views/admin/product/edit.blade.php
@extends('admin.layouts.master')
<link rel="stylesheet" href="{{ asset('assets/adminForm.css') }}">

@section('content')
<div class="content">
    <div class="kt--bg-header kt--pd-20">
            <h3>Product</h3>
    </div>
    <div class="kt--pd-100">
        <div>
            @if(session()->has('success'))
            <div class="alert alert-success" >
                {{ session()->get('success') }}
            </div>
            @endif
            @if(session()->has('failed'))
            <div class="alert alert-success" >
                {{ session()->get('failed') }}
            </div>
            @endif
        </div>
        <form method="POST" action="{{ route('product.update',$product)}}" enctype="multipart/form-data">
            @csrf
            @method('PUT')

            <div class="form-row kt--mgb-20">
                <div class="form-group col-md-4 is-focused">
                    <label for="">Category</label>
                    <div class="input-group mb-3">
                        <select id="category" name="category_id" class="custom-select form-control form-control @error('category_id') is-invalid @enderror" id="inputGroupSelect02">
                            <option  value="{{$product->producttype->category->id}}">{{$product->producttype->category->name}}</option>
                        @foreach ($categories as $category)
                            <option value="{{$category->id}}">{{$category->name}}</option>
                        @endforeach
                        </select>
                        @error('category_id')
                        <span class="error invalid-feedback">{{$message}}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group col-md-4 is-focused">
                    <label for="">Product Type</label>
                    <div class="input-group mb-3">
                        <select id="producttype" name="producttype_id" class="custom-select form-control form-control @error('producttype_id') is-invalid @enderror" id="inputGroupSelect02">
                        <option  value="{{$product->producttype->id}}">{{$product->producttype->name}}</option>

                        </select>
                        @error('producttype_id')
                        <span class="error invalid-feedback">{{$message}}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group col-md-4 is-focused">
                    <label for="">Vendor</label>

                    <div class="input-group mb-3">
                        <select id="vendor" name="vendor_id" class="custom-select form-control form-control @error('vendor_id') is-invalid @enderror" id="inputGroupSelect02">
                            <option  value="{{$product->vendor->id}}">{{$product->vendor->name}}</option>
                        @foreach ($vendors as $vendor)
                            <option value="{{$vendor->id}}">{{$vendor->name}}</option>
                          @endforeach

                        </select>
                        @error('vendor_id')
                        <span class="error invalid-feedback">{{$message}}</span>
                        @enderror
                    </div>
                </div>


            </div>


            <div class="form-row kt--mgb-20">
              <div class="form-group col-md-6 is-focused">
                <label for="inputName">Name</label>
                <input name="name" value="{{$product->name}}" type="text" class="form-control form-control @error('name') is-invalid @enderror" id="inputName">
                @error('name')
                    <span class="error invalid-feedback">{{$message}}</span>
                @enderror
              </div>
              <div class="form-group col-md-6 is-focused">
                <label for="inputStock">Stock</label>
                <input name="stock" value="{{$product->stock}}" type="text" class="form-control form-control @error('stock') is-invalid @enderror" id="inputStock">
                @error('stock')
                    <span class="error invalid-feedback">{{$message}}</span>
                @enderror
              </div>
            </div>
            <div class="form-row kt--mgb-20">
                <div class="form-group col-md-6 is-focused">
                  <label for="inputPrice">Price</label>
                  <input name="price" value="{{$product->price}}" type="text" class="form-control form-control @error('price') is-invalid @enderror" id="inputPrice">
                  @error('price')
                      <span class="error invalid-feedback">{{$message}}</span>
                  @enderror
                </div>


            </div>

            <div class="form-row kt--mgb-20">

                <div class="form-group col-md-12 is-focused">
                  <label for="inputDescription">Description</label>
                  <textarea  name="description" rows="6" class="form-control form-control @error('description') is-invalid @enderror" id="inputDescription">
                     {{$product->description}}
                  </textarea>
                  @error('description')
                      <span class="error invalid-feedback">{{$message}}</span>
                  @enderror
                </div>
            </div>


            <div class="custom-file kt--mgt-20" id="uploadForm">
                <input type="file" name="image"  id="file">
            </div>
            <img src="{{ asset('uploads/'.$product->image) }}" width="200px" alt="" srcset="">

            <div class="kt--mgt-20">
                <button type="submit" class="btn btn-primary float-right">Update</button>
            </div>

          </form>
    </div>

</div>


@endsection

resources/views/admin/product/index.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
                <div class="col-md-6">
                   <button class="btn btn-danger" id='product-deleteAllCheckbox' >Delete Selected</button>
                </div>
                <div class="col-md-6 ">
                    <a class="btn btn-success float-right" href="{{ route('product.create') }}">
                    Add
                    </a>
                </div>
        </div>
        <div>
            @if(session()->has('success'))
            <div class="alert alert-success" >
                {{ session()->get('success') }}
            </div>
            @endif
            @if(session()->has('failed'))
            <div class="alert alert-success" >
                {{ session()->get('failed') }}
            </div>
            @endif
        </div>
      <div class="row">
        <div class="col-md-12">
          <div class="card">

            <div class="card-body">
              <div class="table-responsive">
                <table class="table">
                  <thead class=" text-primary">
                    <tr>
                    <th>
                        <input type="checkbox" name="" id="product-selectAllCheckbox">
                    </th>
                    <th>
                      ID
                    </th>
                    <th>
                      Name
                    </th>
                    <th>
                        Description
                    </th>
                    <th>
                        Stock
                    </th>
                    <th>
                        Price
                    </th>
                    <th>
                      Image
                    </th>
                    <th>
                        Setting
                    </th>
                  </tr></thead>
                  <tbody>

                    @foreach ($products as $key => $product)
                        <tr>
                            <td>
                                <input type="checkbox" name="product[]" id="" value="{{$product->id}}">
                            </td>
                            <td><p>{{$key+1}}</p></td>
                            <td><p>{{$product->name}}</p></td>
                            <td>
                                <p>{{$product->description}}</p>
                            </td>
                            <td>{{$product->stock}}</td>
                            <td>${{$product->price}}</td>
                            <td>
                                <img src="{{ asset('uploads/'.$product->image) }}" width="100" alt="" srcset="">
                            </td>
                            <td style="width: 20%">
                                <a href="{{ route('product.edit',$product->id) }}" class="btn btn-primary">
                                        <span class="material-icons">construction</span>
                                </a>
                                <button id="product-{{$product->id}}" onclick="confirmDelete({{$product->id}},'product')" data-id="{{$product->id}}" data-name="{{$product->name}}" class="btn btn-danger">
                                    <span class="material-icons">delete</span>
                                    <form action="{{ route('product.destroy',$product->id)}}" hidden method="POST">
                                        @csrf
                                        @method('DELETE')
                                    </form>
                                </button>

                            </td>
                        </tr>
                    @endforeach


                  </tbody>
                </table>
                <div style="display:flex;justify-content: center">
                    {{$products->links()}}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


@endsection